name: Deploy Jekyll site from /website

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby (3.2)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Update RubyGems & install Bundler
        run: |
          gem update --system --no-document
          gem install bundler -N -v "~> 2.5"

      - name: Ensure Linux platforms in lockfile (idempotent)
        run: |
          bundle lock --add-platform x86_64-linux || true
          bundle lock --add-platform ruby || true
        working-directory: website

      - name: Install gems
        run: bundle install --jobs 4 --retry 3
        working-directory: website

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build \
          --source website \
          --destination _site \
          --baseurl "${{ steps.pages.outputs.base_path }}"
        working-directory: website

      - name: Debug built files
        run: |
          echo "Contents of website/_site after build:"
          ls -R website/_site | head -50

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
